# fly.toml app configuration file generated for commit2consumer-backend on 2025-08-15T21:53:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'commit2consumer-backend'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8080
  force_https = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "vector_data"
  destination = "/app/data"